specs_ext: [edge_esxi]
nodes:
  webapi: [192.168.2.61]
  vnmgr: [192.168.2.61]
  vna: [192.168.2.61, 192.168.2.62, 192.168.2.63, 192.168.2.60, 192.168.2.65]

webapi:
  host: 192.168.2.61
  port: 9090

vnet_branch: master
vnet_path: /opt/axsh/wakame-vnet
update_vnet_via: "git",

ssh_quiet_mode: true

log_level: debug

dataset_options:
  physical_port: eth0
  edge_port: eth2
  edge_ipv4_address: 172.16.20.10
  edge_esxi_ipv4_address: 172.16.20.9
  dp1_ipv4_address: 172.16.20.11
  dp2_ipv4_address: 172.16.20.12
  dp3_ipv4_address: 172.16.30.11
  public_ipv4_network: 172.16.20.0
  public_ipv4_prefix: 24
  public_ipv4_address1: 172.16.20.20
  public_ipv4_address2: 172.16.20.21
  public_dhcp_ipv4_address: 172.16.20.3
  public_router_ipv4_address: 172.16.20.4

legacy_machines:
  legacy1:
    ssh_ip: 192.168.2.64
    ipv4_address: 10.101.0.100
  legacy_esxi:
    hostname: legacy-esxi
    ssh_ip: 192.168.2.66
    ipv4_address: 10.101.0.101
