site_name: OpenVnet
site_favicon: favicon.png
site_description: Documentation for OpenVnet

theme: readthedocs
docs_dir: content
use_directory_urls: true

repo_url: https://github.com/axsh/openvnet

copyright: Copyright &copy; 2015, <a href="http://axsh.jp/">Axsh Co. Ltd.</a>.
#google_analytics: ['UA-xxxxxxx-x', 'domain.com']

pages:
- ['index.md', 'Home']
- ['concept.md', 'Concept']
- ['installation.md', 'Getting started', 'Installation']
- ['community.md', 'Support', 'Community']

