site_name: OpenVNet
site_favicon: favicon.png
site_description: Documentation for OpenVNet

theme: readthedocs
docs_dir: content
use_directory_urls: true

repo_url: https://github.com/axsh/openvnet

copyright: Copyright &copy; 2015, <a href="http://axsh.jp/">Axsh Co. Ltd.</a>.
google_analytics: ['UA-63388719-2', 'auto']

pages:
- 'Home': 'index.md'
#- 'Concept': 'concept.md'
- 'Installation' : 'installation.md'
- Creating virtual networks:
  - 'Single network': 'single-network.md'
  - 'Single network with DHCP server': 'single-network-dhcp.md'
  - 'Two networks': 'two-networks.md'
  - 'Two network with router': 'two-networks-router.md'
- Configuration files: 'configuration-files.md'
- Vnctl:
  - 'interfaces': 'vnctl-interfaces.md'
  - 'networks'  : 'vnctl-networks.md'
- Debugging:
  - 'vnflows-monitor': 'debugging/vnflows-monitor.md'
  - 'troubleshooting': 'debugging/troubleshooting.md'
- 'Community': 'community.md'
